# Generated by Django 2.0.5 on 2018-05-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='embedded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author3', models.CharField(max_length=100)),
                ('title3', models.CharField(max_length=300)),
                ('text3', models.TextField()),
                ('image3', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='general',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author1', models.CharField(max_length=100)),
                ('title1', models.CharField(max_length=300)),
                ('text1', models.TextField()),
                ('image1', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='imagepro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author5', models.CharField(max_length=100)),
                ('title5', models.CharField(max_length=300)),
                ('text5', models.TextField()),
                ('image5', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author4', models.CharField(max_length=100)),
                ('title4', models.CharField(max_length=300)),
                ('text4', models.TextField()),
                ('image4', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='robotics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author2', models.CharField(max_length=100)),
                ('title2', models.CharField(max_length=300)),
                ('text2', models.TextField()),
                ('image2', models.FileField(upload_to='')),
            ],
        ),
    ]
