# Generated by Django 2.0.5 on 2018-05-20 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedded',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='embedded',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='general',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='general',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='imagepro',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagepro',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='robotics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='robotics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
