# Generated by Django 2.0.5 on 2018-05-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0003_auto_20180520_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedded',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='embedded',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='general',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='general',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='imagepro',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagepro',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=345),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='robotics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=245),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='robotics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
